output "document_bucket" { value = aws_s3_bucket.documents.id }
output "api_repository_url" { value = aws_ecr_repository.api.repository_url }
output "web_repository_url" { value = aws_ecr_repository.web.repository_url }
output "ecs_cluster_name" { value = aws_ecs_cluster.main.name }
output "cross_ibu_registry_table" { value = aws_dynamodb_table.trade_finance_registry.name }
output "ecs_task_role_arn" { value = aws_iam_role.ecs_task.arn }
output "ci_deploy_role_arn" { value = try(aws_iam_role.ci_deploy[0].arn, null) }
output "kms_key_arn" { value = aws_kms_key.documents.arn }
output "application_secret_arn" { value = aws_secretsmanager_secret.application.arn }
output "rds_master_secret_arn" { value = aws_db_instance.postgres.master_user_secret[0].secret_arn }
output "rds_endpoint" { value = aws_db_instance.postgres.address }
output "redis_endpoint" { value = aws_elasticache_replication_group.redis.primary_endpoint_address }
output "staging_url" { value = "http://${aws_lb.demo.dns_name}" }
output "ecs_api_service" { value = aws_ecs_service.api.name }
output "ecs_web_service" { value = aws_ecs_service.web.name }
output "ecs_security_group_id" { value = aws_security_group.ecs.id }
output "ecs_subnet_ids" { value = local.subnet_ids }
